### ISSUE TITLE
cm_refresh Failed calling phpactor

### ISSUE THREAD

**Issue by phatsk** [roxma/ncm-phpactor#4]
Error from logs:
```
2017-11-22 11:25:55,754 [DEBUG @ phpactor.py:cm_refresh:60] 28758 - args: ['php', '/Users/phatsk/.config/nvim/plugged/phpactor/bin/phpactor', 'complete', '--format=json', 'stdin', '17891'], result: []
2017-11-22 11:25:55,754 [ERROR @ cm.py:on_notification:267] 28758 - Failed processing method: cm_refresh, args: [{'scopes': ['php'], 'cm_refresh_patterns': ['-\\>', '::'], 'early_cache': 1, 'name': 'phpactor', 'priority': 9, 'enable': True, 'auto_popup': 1, 'sort': 1, 'scoping': True, 'cm_refresh_length': 3, 'channel': {'id': 9, 'module': 'cm_sources.phpactor', 'events': [], 'type': 'python3'}, 'abbreviation': 'php', 'word_pattern': '[$\\w]+'}, {'scope_match': 'php', 'lnum': 636, 'bufnr': 1, 'changedtick': 105, 'typed': 'outputHelp', 'base': 'outputHelp', 'filetype': 'php', 'curpos': [0, 636, 11, 0, 11], 'col': 11, 'early_cache': False, 'filepath': '/Users/phatsk/src/tools/ao-migrations/import-new-site.php', 'scope': 'php', 'force': 0, 'startcol': 1, 'match_end': 0}]
Traceback (most recent call last):
  File "/Users/phatsk/.config/nvim/plugged/nvim-completion-manager/pythonx/cm.py", line 264, in on_notification
    func(*args)
  File "/Users/phatsk/.config/nvim/plugged/ncm-phpactor/pythonx/cm_sources/phpactor.py", line 62, in cm_refresh
    result = json.loads(result)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The command I ran:

```
echo import-new-site.php|'php' '/Users/phatsk/.config/nvim/plugged/phpactor/bin/phpactor' 'complete' '--format=json' 'stdin' '17891'
```

The console output:

```
  [InvalidArgumentException]
  Could not locate autoloaderPath file "/Users/phatsk/src/tools/ao-migra
  tions/vendor/autoload.php"
```

**Comment by dantleech** [comment]
Phpactor currently depends on composer being used (and the `autoloader.php` file being present). But, it would be possible to avoid this.

Please raise an issue in https://github.com/phpactor/phpactor however.
